---
- name: Cachefilesd | Installing cachefilesd
  sudo: yes
  apt:
    pkg: cachefilesd
    state: "{{ cachefilesd_package_state }}"
    update_cache: yes
    cache_valid_time: 3600

- name: Cachefilesd | Enable cachefilesd
  sudo: true
  template:
    src: cachefilesd.tpl
    dest: /etc/default/cachefilesd
